// components/About/index.tsx
import React from 'react'

import Section from '../Section'
import SectionHeading, { Small } from '../SectionHeading'
import './styles.scss'

export const SCROLL_TARGET_ID_ABOUT = 'about'

const About = () => {
	return (
		<Section id={SCROLL_TARGET_ID_ABOUT}>
			<div className="container mx-auto max-w-screen-xl">
				<SectionHeading
					title={
						<>
							Intro <Small>about me</Small>
						</>
					}
					subtitle="Father of two, husband and Major Explorer of this vast web development universe."
				/>

				<div className="grid grid-cols-1 md:grid-cols-[60%_1fr] xl:grid-cols-2">
					<div className="mx-12 flex flex-col justify-center leading-relaxed md:mr-0 md:text-sm lg:text-base">
						<p className="mb-4">
							It’s been about 10 years since I accepted the mission and took off in my spaceship to
							the vast Web Developer Universe. It was a turbulent start with huge IE6 time sinks and
							painful plain CSS2 styles sheets. New mobile technology had arrived in the cosmos and
							I managed to change my old Flash engine into a new JavaScript based engine and was
							able to travel several light years ahead.
						</p>
						<p className="mb-4">
							Awesomely built, easy-to-use fast apps are truly a passion of mine. I actively seek
							out new ‘planets’ and technologies, exploring the unknown parts of the galaxy to stay
							up-to-date not only with the latest industry trends but also any ‘alien’ advanced
							technology. ;)
						</p>
						<p className="mb-4">
							If you are an explorer, like me, willing to know more about things, go straight to my
							Bahance and my Git Hub profile, where this angular website is there for you to explore
							at will.
						</p>
						<p className="mb-4">
							Intergalactic messages can be sent to my e-mail contact@tiagodonatti.net
						</p>
						<p>
							<strong>Live long and prosper</strong>
						</p>
					</div>
					<div className="ship-container">
						<img className="ship" src="images/ship.svg" />
						<div className="ship-background">
							<img src="images/ship-background.svg" />
						</div>
					</div>
				</div>
			</div>
		</Section>
	)
}

export default About

// src/app/home/about/about.component.ts
import { animate, state, style, transition, trigger } from '@angular/animations';
import { Component, ElementRef, HostListener, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss'],
  animations: [
    trigger('scrollAnimation', [
      state('showShip', style({
        opacity: 1,
        transform: 'translateY(0)'
      })),
      state('hideShip',   style({
        opacity: 0,
        transform: 'translateY(50%)'
      })),
      transition('showShip <=> hideShip', animate('1200ms ease-out'))
    ])
  ]

})
export class AboutComponent implements OnInit {

  state = 'hideShip';

  constructor(
    public el: ElementRef
  ) { }

  ngOnInit() {
  }


  @HostListener('window:scroll', ['$event'])

  checkScroll() {
    const componentPosition = this.el.nativeElement.offsetTop;
    const scrollPosition = window.pageYOffset;

    if (scrollPosition >= componentPosition) {
      this.state = 'showShip';
    } else {
      this.state = 'hideShip';
    }
  }

}

<section id="about">

  <div class="container">

    <div class="row">
      <div class="col">
        <div class="section-heading">
          <h3 class="section-title">Intro <small>about me</small></h3>
          <h4 class="section-subtitle">Father of two, husband and Major Explorer in this vast web development universe.</h4>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="about-text">
          <p>It’s about 10 years since I accepted the mission and take out in this space ship to the vast web developer universe. Was a turbulent start with huge IE6 time sinks and painful plain CSS2 styles sheets. New mobile technology has arrived in the cosmos and I managed to change my old Flash engine to a new JavaScript based engine and was able to travel several light years forward.</p>
          <p>Build awesome, easy to use and fast apps is truly a passion of mine. I actively seek out new planets and technologies, exploring the unknown parts of the galaxy to stay up-to-date on industry trends and alien advance technology.</p>
          <p>If you are an explorer, like me, and seek to know more, go straight to my Bahance and my Git Hub profile, where this angular website is there to you to explore at will.</p>
          <p>Intergalactic message can be sent to contact@tiagodonatti.ca</p>
          <p><strong>Live long and prosper</strong></p>

        </div>
      </div>
      <div class="col-md-6 position-relative">
        <div class="ship">
          <img [@scrollAnimation]="state" src="assets/img/ship.svg">
          <div class="ship-background">
            <img src="assets/img/ship-background.svg">
          </div>
        </div>

      </div>
    </div>
  </div>

</section>
